[program:fs_sync]
command=/home/s0nnet/venv/bin/python /home/s0nnet/trunk/fs_data_sync/src/sync_main.py
autorestart=true
autostart=true
stdout_logfile= /home/s0nnet/logs/fs_sync_stdout.log
stderr_logfile= /home/s0nnet/logs/fs_sync_stderr.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
numprocs=1
numprocs_start=0
user=s0nnet
